### ISSUE TITLE
Ground station marker

### ISSUE THREAD

**Issue by EwoudSmeur** [Fabien-B/GcsAgain#10]
In the old GCS, it was possible to display the position of the ground station on the map by sending the following message on the IVY bus:
`IvySendMsg("ground FLIGHT_PARAM GCS %f %f %f %f %f %f %f %f %f %f %f %d %f",`

It would be great to have this in the new GCS as well. It would be even better if would be possible to include a heading for the ground station symbol as well, so that if the base is moving the heading can be displayed on the map.

**Comment by EwoudSmeur** [comment]
Additionally, dark black is not a great background for most waypoint colors. Is it already possible to change the default background color of the GCS map, for instance to gray? It should be easier to see the waypoints on such a background.

**Comment by Fabien-B** [comment]
I did not know about this feature, I will add it soon.
The customization of the GCS is not yet very good, but this will be improved! Its now possible to change the default background color, with https://github.com/Fabien-B/PprzGCS/commit/c0e859375d6b8d34ada30bfd622ff0017e1a44ec.
You have to edit the `MapWidget` class in the `default_style.qss` file. Find it with File->Open app directory.

You can make a copy of this file but you will have to edit the path in `settings.conf` (File->Open user directory). Like I said, this will be improved...

**Comment by EwoudSmeur** [comment]
Thanks @Fabien-B! Will try it out soon 😃

**Comment by Fabien-B** [comment]
If you use the .deb I need to add a new version tag to rebuild the deb. I will probably wait after I implement the GCS position.
If you build from sources, well, you can do what you want :smile:

**Comment by EwoudSmeur** [comment]
Thanks for the tip, I'll try building from source!

**Comment by EwoudSmeur** [comment]
I'm having some issues with building from source. First I noticed that I did not have CMake, maybe this can be added to the dependencies. Then, it seems like he is looking for the CMakeLists.txt in the wrong directory:
```
ewoud@ubuntu:~/PprzGCS$ ./build.sh libs
install_prefix set to /home/ewoud/PprzGCS/build/install.
CMake Error: The source directory "/home/ewoud/PprzGCS/ext/IvyQt" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
I'm not sure what to do here, do you have a tip?

**Comment by Fabien-B** [comment]
Oh sorry, I should add in the readme and probably also in the script, you need to update submodules first.
run `git submodule update --init --recursive` before running the script.

**Comment by EwoudSmeur** [comment]
Thanks, that works!
I was still wondering the following: I can start the GCS from paparazzi center by giving the full path, but not with simply 'pprzgcs'. I thought that was the intention behind adding it to the PATH variable.

**Comment by Fabien-B** [comment]
Yep, You're right. Just made the PR we need :smile: 
https://github.com/paparazzi/paparazzi/pull/2780

**Comment by Fabien-B** [comment]
The GCS marker is now implemented.
You can change its color and size via the `gcs_icon_color` and `gcs_icon_size` keys in the `settings.conf` file (File->Open user directory).

**Comment by EwoudSmeur** [comment]
That is great @Fabien-B, thank you so much! Do I understand correctly that it will show upon receiving the FLIGHT_PARAM message with ac_id="GCS"?

**Comment by Fabien-B** [comment]
Yes, like in the old one. It has to be a valid FLIGHT_PARAM message of course.
