### ISSUE TITLE
Install through apt missing module

### ISSUE THREAD

**Issue by fvantienen** [Fabien-B/GcsAgain#13]
When I installed `pprzgcs` through apt it starts normally but gives the following warning/error in the cmdline:
```
Gtk-Message: 10:57:57.221: Failed to load module "appmenu-gtk-module"
```

Maybe some package is missing? I'm running ubuntu 20.04.1

**Comment by Fabien-B** [comment]
Any link with this issue ? https://github.com/paparazzi/paparazzi/issues/2603
Is it doing that just when launched from the Paparazzi Center, or also from a terminal ?

**Comment by fvantienen** [comment]
Both actually and the package `appmenu-gtk2-module` is installed. The GCS runs, but I still get this message

**Comment by fvantienen** [comment]
I installed `appmenu-gtk3-module` and then I don't get the warning anymore. Maybe we can add that one to the dependencies as well?

**Comment by Fabien-B** [comment]
I added it to the control file, it will be fixed in the next released.
