### ISSUE TITLE
Flight plan details not visible

### ISSUE THREAD

**Issue by EwoudSmeur** [Fabien-B/GcsAgain#7]
I noticed you can view the flight plan blocks in the 'details' panel, but the contents of the block elements do not show it just says e.g. 'exception'. Sometimes it can be really useful to see the flight plan from the GCS in order to understand what a drone is doing or will do, so it would be cool to be able to see all of the flight plan in the details panel.

**Comment by Fabien-B** [comment]
I might just be size of the columns, try expanding the first column.
The child nodes should be displayed in the top widget, and all attributes should be displayed on the bottom one.

Some details are also displayed in the second column of the top widget, and you are right, more should be displayed.

Also (not your problem here, but for the future), note that the library used for this widget is not very tolerant to XML syntax errors. In particular, be sure there are no forbidden characters in you flight plan: >, <, &... and replace them by `@GT` `@LT` `@AND`, ...

**Comment by Fabien-B** [comment]
# Display info for flight plan nodes

- [x] block : block name
- [x] waypoint: waypoint name
- [x] sector: sector name (and color?)
- [x] variable: name
- [x] module: name
- [x] exception: condition? deroute block ?
- [x] call / call_once: function called
- [ ] ...

**Comment by Fabien-B** [comment]
@EwoudSmeur is it better now with v1.0.4?
https://github.com/Fabien-B/PprzGCS/releases/tag/v1.0.4

**Comment by EwoudSmeur** [comment]
That is so nice, thanks a lot! Maybe there is one small improvement that could be done, and that is that If you have an 'attitude' in a block it will just give one number as the argument, in this case 0:
`<attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>`
becomes
attitude 0

Otherwise great!!

**Comment by Fabien-B** [comment]
It already does that, unless I don't understand what you mean:
```
<block name="Holding point">
      <set value="1" var="autopilot.kill_throttle"/>
      <attitude roll="0" throttle="0" vmode="throttle"/>
</block>
```
renders to:

![image](https://user-images.githubusercontent.com/7016951/131515451-a43df5d4-777d-4eca-a7c5-bed29ca67d02.png)
Right now it prints the roll attribute.
But if you have other ideas, don't hesitate!

**Comment by EwoudSmeur** [comment]
Indeed, so you can't see if there are any other attributes, or what the vmode is. In the old GCS you can see the entire line with all attributes. It would be nice to have, but I don't think this is very critical.

**Comment by Fabien-B** [comment]
I could do that but I think it would become unreadable: the line will be too long.
This is why all attributes are shown in the tree below.
The second column of the top tree is just a summary to ease readability.
![image](https://user-images.githubusercontent.com/7016951/131695816-e7ed3f15-9890-479f-9f6b-4668356aefc9.png)

**Comment by EwoudSmeur** [comment]
Oh sorry I hadn't seen that! That is an excellent solution! I think with that we can close this issue :)
