### ISSUE TITLE
Cannot build due to libqt5texttospeech5-dev needed 

### ISSUE THREAD

**Issue by OpenUAS** [Fabien-B/GcsAgain#8]
The instruction on  https://fabien-b.github.io/PprzGCS/developer_guide/how_to_build.html#  fail to mention   to add   `libqt5texttospeech5-dev` needed to build.

`sudo apt install libxml2 libzip5 libproj15 libqt5xml5 libqt5network5 libqt5svg5 libqt5texttospeech5 libqt5widgets5 libqt5gui5 libqt5core5a libqt5texttospeech5-dev`

Fixes it after on got this bla bla ```
 CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5TextToSpeech"
  with any of the following names:

    Qt5TextToSpeechConfig.cmake
    qt5texttospeech-config.cmake

  Add the installation prefix of "Qt5TextToSpeech" to CMAKE_PREFIX_PATH or
  set "Qt5TextToSpeech_DIR" to a directory containing one of the above files.
  If "Qt5TextToSpeech" provides a sep
```

**Comment by OpenUAS** [comment]
IMHO, at the current state of project maybe best to keep developer docs in https://github.com/Fabien-B/PprzGCS/blob/master/Readme.md  and the rest of the documentation for users in https://fabien-b.github.io/PprzGCS/index.html or better generate it then from other files also in Github.

To add improvements to the project should be as easy to edit the MD or make a Pull/Merge request. As a developer you come across thing one could quickly improve, but if the process is to , takes away to much time, most of the time one

**Comment by Fabien-B** [comment]
You are right, I will improve the Readme, and add the missing dependency.
And I know its not that easy, but the doc in https://fabien-b.github.io/PprzGCS is automatically build from the docs directory, so any PR in it will update the doc immediately.

**Comment by Fabien-B** [comment]
And BTW, the packet you are missing is `libqt5texttospeech5-dev`
