### ISSUE TITLE
Improve current startup

### ISSUE THREAD

**Issue by OpenUAS** [Fabien-B/GcsAgain#9]
As a use one simply want  to startup an application. The "old GCS" did no require environment variable per se to still work. An applicatin should not need ENV to function, but now does:

`env PAPARAZZI_HOME and PAPARAZZI_SRC must be set!`

**Comment by Fabien-B** [comment]
Hi, I do not know exactly how to do the startup properly, but I do think the old GCS need some environment variables, or else it crashes with `Fatal error: exception Xml.File_not_found("/usr/share/pprzlink/messages.xml")`.
The thing is that the Paparazzi center set theses variables for us.
So to have the same behavior, you need to add a tool to the paparazzi center, and launch PprzGCS from the paparazzi center.
Go to paparazzi/conf/tools, and add a file on the model of the other files.
Then restart paparazzi, and launch PprzGCS via the `Tools` menu.

Do you think I should add this file to the paparazzi master ?

Thank you very much for testing it!
